### PR TITLE
Add Subsplease

### PR DESCRIPTION
**Pull request by vvirtues**
Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio
- [x] Have removed `web_hi_res_512.png` when adding a new extension
- [x] Have made sure all the icons are in png format

### CODE REVIEW

**Comment by vvirtues** [comment]
how do i test it
i opened in android studio what now

**Comment by vvirtues** [comment]
image
guess it works

**Comment by vvirtues** [comment]
image
guess it works

**Comment by mobby45** [comment]
to test it, install aniyomi on and launch it

**Comment by vvirtues** [comment]
Yes it works with aniyomi

**Comment by mrtear** [comment]
> Yes it works with aniyomi

@vvirtues (sry for the @)
I know it’s weird to receive a reply to a closed issue, but…

I noticed that the SubsPlease extension isn’t working on the official Aniyomi app, but it works on forks of Aniyomi that support torrents. Have you tested it with Aniyomi forks or the official app? Should I open an issue on github?
error

**Comment by vvirtues** [comment]
no its meant for torrents

> > Yes it works with aniyomi
> 
> @vvirtues (sry for the @) I know it’s weird to receive a reply to a closed issue, but…
> 
> I noticed that the SubsPlease extension isn’t working on the official Aniyomi app, but it works on forks of Aniyomi that support torrents. Have you tested it with Aniyomi forks or the official app? Should I open an issue on github? error

**Pull request merged**
